[package]
name = "ferris_ripper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "*"
sha1 = "*"
hex="*"
structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"
